/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About2: typeof import('./src/components/about2.vue')['default']
    Aboutpg: typeof import('./src/components/aboutpg.vue')['default']
    All_journals: typeof import('./src/components/all_journals.vue')['default']
    Collection: typeof import('./src/components/collection.vue')['default']
    ComingSoon: typeof import('./src/components/ComingSoon.vue')['default']
    Contact: typeof import('./src/components/contact.vue')['default']
    Hexpalette: typeof import('./src/components/hexpalette.vue')['default']
    Homepg: typeof import('./src/components/homepg.vue')['default']
    OAuthSuccess: typeof import('./src/components/OAuthSuccess.vue')['default']
    OrderDetails: typeof import('./src/components/OrderDetails.vue')['default']
    OrderStatus: typeof import('./src/components/orderStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Saree_jornal: typeof import('./src/components/saree_jornal.vue')['default']
    Toast: typeof import('./src/components/common/Toast.vue')['default']
    TrackStatus: typeof import('./src/components/TrackStatus.vue')['default']
    UserLogin: typeof import('./src/components/userLogin.vue')['default']
    Userregister: typeof import('./src/components/userregister.vue')['default']
  }
}
